<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;net6.0;net7.0;net8.0</TargetFrameworks>
    <PackageVersion>2.24.1</PackageVersion>
    <AssemblyVersion>2.24.1</AssemblyVersion>
    <FileVersion>2.24.1</FileVersion>
    <LangVersion>latest</LangVersion>
    <TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>
    <ImplicitUsings>enable</ImplicitUsings>
    <PackageId>Thirdweb</PackageId>
    <Title>Thirdweb</Title>
    <Authors>0xfirekeeper</Authors>
    <Description>Best in class Web3 .NET SDK, powered by thirdweb.</Description>
    <Copyright>Copyright (c) thirdweb 2024</Copyright>
    <PackageProjectUrl>https://thirdweb.com/</PackageProjectUrl>
    <PackageIcon>icon.png</PackageIcon>
    <RepositoryUrl>https://github.com/thirdweb-dev/dotnet</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>thirdweb wallet contracts client web3 ethereum blockchain game unity godot</PackageTags>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
  </PropertyGroup>
  <PropertyGroup>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Nethereum.ABI" Version="4.19.0" />
    <PackageReference Include="Nethereum.Hex" Version="4.19.0" />
    <PackageReference Include="Nethereum.Contracts" Version="4.19.0" />
    <PackageReference Include="Nethereum.Signer" Version="4.19.0" />
    <PackageReference Include="Portable.BouncyCastle" Version="1.9.0" />
    <PackageReference Include="Nethereum.Signer.EIP712" Version="4.19.0" />
    <PackageReference Include="Nethereum.HdWallet" Version="4.14.0" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
    <None Include="..\resources\icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
