name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: build-and-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test-cov:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup
        uses: actions/setup-dotnet@b2ace4b12f4cec1b96b6361ff2694ba9e931ceb4 # v3.3.1
        with:
          dotnet-version: |
            8.0.x

      - name: Restore
        run: dotnet restore
        working-directory: ./

      - name: Build
        run: dotnet build --no-restore -c Release
        working-directory: ./

      - name: Test
        id: test
        run: |
          dotnet tool install --global coverlet.console
          timeout 30m dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=./coverage.info
        shell: bash
        env:
          THIRDWEB_SECRET_KEY: ${{ secrets.THIRDWEB_SECRET_KEY }}
          THIRDWEB_CLIENT_ID_BUNDLE_ID_ONLY: ${{ secrets.THIRDWEB_CLIENT_ID_BUNDLE_ID_ONLY }}
          THIRDWEB_BUNDLE_ID_BUNDLE_ID_ONLY: ${{ secrets.THIRDWEB_BUNDLE_ID_BUNDLE_ID_ONLY }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

      - name: Codecov
        if: always() && steps.test.outcome != 'cancelled'
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4.6.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./
          verbose: true
          slug: thirdweb-dev/dotnet
